### PR TITLE
add option to fetch multiple books and coverage for multiple books

### PR DESCRIPTION
**Pull request by philschatz**
Adds ability to run the following:

- `./scripts/fetch-book --all` which updates all the books.
- `./scripts/report-book-coverage --all` generates CSS coverage of all fetched books

# Observations

`./scripts/report-book-coverage --all --cover-declarations` found several pieces of "dead code", either unused variables or selectors that never matched anything.

**Note:** Some of these might be elements that are created in one pass and then removed in another

## Unused Variables

image

image

## Unmatched Selectors

image

# TODO

- [x] maybe use dennis' suggestions in #61

/cc @reedstrm

### CODE REVIEW

**Comment by helenemccarron** [comment]
I can test whether or not the code is dead. Looking at it, I think many of it is required. I'll make updates as needed in separated PRs

**Comment by helenemccarron** [comment]
`$symbolsSectionTitle: "Symbols";` produces 
```
:pass(5) .os-index-container > div.group-by:first-of-type > span.group-label {
  content: "Symbols"; }
```

**Comment by helenemccarron** [comment]
`$name: map-get($page, name);` is used a little below in the mixin: 
```
      $titleContent: (
        text: $name
        );
```

**Comment by helenemccarron** [comment]
`@include utils_title($titleContent, null, h1, "document-title");` is producing
```
:pass(5) [data-type="composite-page"].os-eoc.os-glossary-container::before {
  container: h1;
  data-type: "document-title";
  content: pending(h1-TITLECONTAINER); }
```

**Comment by helenemccarron** [comment]
`attr-id: uuid() "@1";` is producing
```
:pass(5) div[data-type="composite-page"] {
  attr-id: uuid() "@1"; }
```

**Comment by helenemccarron** [comment]
`    [data-type="cnx-archive-uri"] {
      move-to: trash;
    }`
is producing 
```
:pass(7) div.os-eoc [data-type="cnx-archive-uri"], :pass(7) div.os-eob [data-type="cnx-archive-uri"] {
  move-to: trash; }
```

**Comment by philschatz** [comment]
Ah, drat. I guess it's time to ask @reedstrm to add a feature to easybake to run exactly 1 pass (so I can run the coverage script between each pass) to count all those intermediary selectors/elements

**Comment by helenemccarron** [comment]
I believe that is already possible with `-s <pass>, --stop-at <pass>`? Or am I mistaken?

**Pull request merged**
