### PR TITLE
Bio - fix chapter outline

### LINKED ISSUE #185: Multiple Books => Chapter Introductions missing "Chapter Outline."
# Scenario

Chapter introductions do not include the “Chapter Outline” element.

# Reproducibility Details

* **Impact area**: Content
*  **User**: Name of user that encountered error.
*  **URL / Location**: https://dev00.cnx.org/contents/Ax2o07Ul@9.43:HR_VN3f7@3/11-Introduction-to-Science-and
* **How many times were you able to reproduce the issue?** Most / All Chapters

*  **Steps to reproduce**:

1. Open the book’s [webview version](https://dev00.cnx.org/contents/Ax2o07Ul@9.43:pFeekPiU@14/Preface-to-College-Physics)
2. Expand a chapter in the TOC, and click on the introductory section.
3. Observe the lack of “Chapter Outline."

* **Images or screenshots Included:** Yes  (_attach below_)

image

image

# Environment:

* **Instance**: Dev00
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

### PR DESCRIPTION
**Pull request by caderitter**
Fixes #185 for biology only - physics will be in another PR

### CODE REVIEW

**Comment by helenemccarron** [comment]
@kerwinso please note that the `.introduction` class seems to be missing and that the chapter outline may display in a weird location until the content has been fixed.

**Comment by kerwinso** [comment]
@helenemccarron Where is the `.introduction` class supposed to go? I can try monkeying with the content.

**Comment by helenemccarron** [comment]
I believe on the `content` tag in the introduction module. If that doesn't work, the `document` tag

**Comment by kerwinso** [comment]
@caderitter @helenemccarron Just rebaked Bio on dev ([link](https://dev.cnx.org/contents/GFy_h8cu@10.63:djajv-uA@2/Introduction)). The Chapter Outline is there, but the links are missing the section number, e.g. `Water` should be `2.2: Water` to match the PDF. I think this should be fixed.

image

**Comment by caderitter** [comment]
We're moving this change to #243 to make merging simpler

**Pull request closed without merging**
