### PR TITLE
Empty compound composite child pages are no longer titled

### PR DESCRIPTION
**Pull request by tomjw64**
[Errata 4476](https://openstax.org/errata/4476) resolved via recipe change. Additionally, removes delete-me's missed by easybake as part of the end of bake clean up (as it was required to do so to resolve the issue, and also seems like a reasonable thing to do)

### CODE REVIEW

**Comment by philschatz** [comment]
Does this attempt to fix a bug in `cnx-easybake` (just asking from the message in the PR description)?

**Comment by kerwinso** [comment]
Related Trello card: https://trello.com/c/zu9xLIbn/326-empty-exercise-headers-in-webview

**Comment by tomjw64** [comment]
@philschatz It does attempt to solve an issue with easybake. I would definitely prefer not to, but I could see no good alternative way of removing the header.

**Comment by reedstrm** [comment]
This does not fix the easybake bug - it works around it.

**Comment by tomjw64** [comment]
@reedstrm yes, you're correct. I should have watched my wording a little more closely.

**Pull request merged**
