### PR TITLE
remove unused python packages

### PR DESCRIPTION
**Pull request by reedstrm**
Reviving #80, to continue discussion. Helene and I think the validate script is critical and should be added to the scripts.

### CODE REVIEW

**Comment by philschatz** [comment]
cool! what's the command look like to validate?

**Comment by reedstrm** [comment]
I suggest leaving cnx-epub. Probably don't need cnx-archive locally.

**Comment by philschatz** [comment]
oh, do you know what `cnx-archive` could have been used for?

**Comment by reedstrm** [comment]
```
    [console_scripts]
    cnx-archive-initdb = cnxarchive.scripts.initializedb:main
    cnx-archive-hits_counter = cnxarchive.scripts.hits_counter:main
    cnx-archive-inject_resource = cnxarchive.scripts.inject_resource:main
    cnx-archive-export_epub = cnxarchive.scripts.export_epub.main:main
```
So, building the epub, and injecting the CSS.

**Comment by philschatz** [comment]
Closing because this was fixed in #96 😄

**Pull request closed without merging**
