### PR TITLE
Draft an `algebra.html` for discussion

### PR DESCRIPTION
**Pull request by pumazi**
This is the results of doing

```
export epub (returns internal epub) -> transform to single-html (returns html file)
```
which is the first part of
```
export epub (returns internal epub) ->
collate [transform to single-html (returns html file) ->
         cook single-html  (returns html file) ->
         reconstitute (returns models)] (returns models) ->
export to epub (returns epub)
```

### CODE REVIEW

**Comment by InconceivableVizzini** [comment]
`<div data-type="resources" style="display: none;"></div>`

Can this be avoided?

**Comment by pumazi** [comment]
The resources section was a newly created metadata bit that comes out of [Implement the encapsulation of Resources within a Binder](https://trello.com/c/1b73hNXN/31-implement-the-encapsulation-of-resources-within-a-binder).

It's a necessary bit of information which will be needed in the reconstruction of the data back into machine readable data. Basically, all resources are mostly registered by hrefs, src, etc. (aka `Reference`s) in the content, but this isn't the case for Binders/Books, which does not contain content type data and thus contains no references.

**Comment by InconceivableVizzini** [comment]
`<body .....>`

can be

`<body data-type="book">`

-

The "most top level" selector a framework based stylesheet would use.

**Comment by InconceivableVizzini** [comment]
`<div data-type="metadata">`

This should probably just be a section? For my part I think all of the metadata and table of contents should be under a top level section type.

`<section data-type="section" class="titlepage">... metadata ... ...toc ... </section>`

-

Similarly, `<div data-type="page">...</page>`

can be `<section data-type="section">...</section>`

**Comment by InconceivableVizzini** [comment]
Under metadata, `data-type=""` can instead be `class=""` and `data-part=""`. eg, `<h1 data-part="title"></title>` and `<span data-type="cnx-archive-uri">` can be `<span class="cnx-archive-uri">`, etc.

**Comment by InconceivableVizzini** [comment]
For the `id="toc"` nav element, we should investigate further with the various book structures and develop classes for the various parts of the toc. An example of how we use these can be seen with the high school physics design.

**Comment by InconceivableVizzini** [comment]
`<div data-type="document-title">`

Helene and I have ideas with regards to a set of markup for all titles that will allow enough flexibility for all of our designs.

-

Something along the lines of...

`<div data-part="title"><span class="titling" /><span class="titling" /><span class="titling" /><span class="titling" /></div>`

Primarily we tend to require numbering, a divider, a label, and an element to contain the wording (text node). This split gives us enough control for various types of visual distinction, and why we need it can be seen with the high school physics design.

**Comment by InconceivableVizzini** [comment]
`<p id="delete_me"></p>`

Um...

**Comment by helenemccarron** [comment]
avoid different methods for handling titles <div data-type="document-title">  <h2 data-type="title">.

 <div data-type="document-title">  for section titles is confusing.

**Comment by helenemccarron** [comment]
Can we avoid duplicate data-type/class? 
``<div data-type="solution" class="solution" >`` seems redundant

**Comment by InconceivableVizzini** [comment]
After considering the "page" to "section" switch, the old CNXML tag `<section>` becomes strange. I propose these transform into `<div data-type="subsection"></div>` or `<div data-type="topic">...</div>`.


The storage chunk "page" is logically a top level "section" of the book, and I would like the data-types to reflect that. The CNXML "section" is a subheading/subsection in a section of the book.

**Comment by InconceivableVizzini** [comment]
`
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.
All chapters are broken down into multiple sections, the titles of which can be viewed in the Table of Contents.`

In the preface, is this in the content, or is there a bug?

**Comment by InconceivableVizzini** [comment]
`div data-type="abstract">` We need to get together and nail down this whole "Chapter Outline" and "Learning Objectives" stuff...

**Comment by helenemccarron** [comment]
``<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">`` or ``<math xmlns="http://www.w3.org/1998/Math/MathML" display="inline"> ``
Should we avoid inline styles?

**Comment by InconceivableVizzini** [comment]
@helene regarding the math tag, and some other tags, such as svg, inline styles may be unavoidable and is the generally accepted way they are entered into markup. Eg the stroke="" etc attributes. I don't really like this either...

**Comment by helenemccarron** [comment]
``<table id="Table_04_00_01" summary="">`` I can't remember if this applies to algebra but in general, we need to make sure that all classes applied to tables are transferred.

**Comment by pumazi** [comment]
Reply to metadata...

Keep in mind that everything within the `<div data-type="metadata">` block is added by cnx-epub. This block cannot be moved to the top of the document. It needs to remain with the individual documents themselves (for reconstruction). (*In publishing, we remove this block before committing the content to archive.*)

The metadata blocks could potentially be moved to the top of the document and the blocks could be linked by id. But we can't collapse that metadata into one blob without doing a lot of work to parse it back out again.

**Comment by pumazi** [comment]
Replying to titling...

The `data-type="document-title"` is something we add from cnx-epub. The other `<h# data-type="title"`>` is from transforms (cnxml `<title>` -> html `<h# data-type="title">`). So they aren't the same and as such need to be treated differently. For me, using `document-title` was that solution.

In the beginning I started with `<h1>` for the document-title, then ran into issues because that element is actually used in the content. And there needed to be a distinction between the document-title and a title used in the content (for parsing out by xpath).

**Comment by InconceivableVizzini** [comment]
I don't like that this document is tied to any type of logic about reconstruction etc etc... this document should be precisely what we need for rendering, not for any other purpose.

**Comment by pumazi** [comment]
@helenemccarron in response to:

> Can we avoid duplicate data-type/class? 
`<div data-type="solution" class="solution" >` seems redundant

This is done in the transform cnxml->html5. ([xsl snippet of the section where it happens](https://github.com/Connexions/rhaptos.cnxmlutils/blob/master/rhaptos/cnxmlutils/xsl/cnxml-to-html5.xsl#L162-L165)) Looks like we can probably remove this, but I'd suggest we not do those kind of changes at the same time. Let's add an issue to rhaptos.cnxmlutils to remove this?

**Comment by pumazi** [comment]
@InconceivableVizzini in response to
> I don't like that this document is tied to any type of logic about reconstruction etc etc... this document should be precisely what we need for rendering, not for any other purpose.

Please see my awful diagram of inputs and outputs for the various pieces of logic. We do need to reconstruct the cooked html output so that it can be put back into the archive.

If it's the PDF single-html file you are thinking of, **we can create another formatter** (similar to `cnxepub.adapters.SingleHTMLFormatter`) to format the EPUB (models) to a single-html file that contains ONLY what you need.

**Comment by reedstrm** [comment]
Mostly good comments, the expectation is that PDF rendering will start from the encapsulated epub, which will not contain this particular single html file. If you absolutely hate the idea of a few warts to cover the 'cook and burst' case, we could add an option or alternative formatter to strip that out.

I'm envisioning a textbook styling workflow going something like - 
### Textbook-two-step: collation & numbering, then styling

-   install cnx-epub
-    grabbing a full epub, unzipping it locally, 
-    run local cook against that directory with a local  recipe CSS - 
         in this case, local cook does the assemble/cook/burst steps
-    check collation/numbering behavior
-    rinse/repeat
-    update styling
-    check page-by-page style (webview way)
-    generate single-html (potentially sub-sampling)
-    check fullbook styling (in browser, but testing for PDF gen)
-    run pdfgen against directory (includes it's own fullbook assembly step)
-    check PDF
-    commit diffs to book recipe CSS and styling CSS

Alternatively, local cook could leave the 'all one file' around as well as bursting it.

**Comment by pumazi** [comment]
Furthermore, the PDF transform circuit looks more like this:

```
export epub containing cooked contents  (returns internal epub) ->
send to transformation services [
    transform to single-html  (returns html file) ->
    produce pdf  (returns pdf file)
    ]  (returns list of artifacts containing a reference to the pdf)
```

So again, the single-html for the PDF could be a specific adaptation of the models into a format that meets *exactly* what you want.

**Comment by helenemccarron** [comment]
@reedstrm the one thing I am wondering in the scenario you posted is testing. That workflow is perfect for development but how do testers generate the pdf in conditions that are similar to production and ensure that everything will look the same?

Or are we uploading PDF manually all the time, without any pdf generation on the server at all (which means that nobody can create a pdf other than Openstax)?

**Comment by reedstrm** [comment]
@helenemccarron No, the automated PDF generation will use the path @pumazi outlined in the comment directly above yours. :-)

**Comment by pumazi** [comment]
During the moving of elements to composite (or virtual) pages, can we use `data-type="composite-page"` over `data-type="page"`? This will help us in the reconstitution of the models. I have a feeling it will also be beneficial down the line when working with the content in authoring.

**Comment by reedstrm** [comment]
I'm going to close this PR - I think all the comments have been addressed, or documented elsewhere.

**Pull request closed without merging**
