### PR TITLE
Remove Teacher Support from TEA Books

### LINKED ISSUE #250: TEA - HS Physics and AP Bio Teacher Support
# Scenario

TEA does not want to see Teacher Support content. We need to remove them in the recipes

# Reproducibility Details

- **Impact area**: Gateway
- **User**: TEA
- **URL / Location**: Gateway/epub
- **How many times were you able to reproduce the issue?** : all the time

## Steps to reproduce:

- Load the page

## Screenshots

N/A, HS physics isn't in the Gateway at the moment. One way to see it is open the epub, Webview hides it.

# Environment:

- **Instance**: doesn't matter
- **OS**: doesn't matter
- **Browser**: doesn't matter

# Impact

- **Severity**: high
- **Frequency of occurrence**: all the time

### PR DESCRIPTION
**Pull request by tomjw64**
Remove the .os-teacher (Teacher Support) notes for TEA books to resolve issue #250

### CODE REVIEW

**Comment by philschatz** [comment]
Is there an Issue related to this? I don't know if I should merge or assign QA to this PR

**Comment by tomjw64** [comment]
@philschatz It addresses issue #250 , so it should be assigned to QA.

**Comment by kerwinso** [comment]
please assign to @Stackblocks (our resident TEA tester)

**Comment by helenemccarron** [comment]
@philschatz, this came up from Alana requesting we remove them after the TEA commented on them. I don't know if she documented it anywhere else.

**Pull request merged**
